### ISSUE TITLE
If more than 1000 records are sent to a shard in a second no error is thrown

### ISSUE THREAD

**Issue by jmathewt** [NYPL-discovery/bulk-export-reader#19]
Kinesis has a limit that only 1000 records can be sent to a shard in a second. Using the node client library for aws, even if we send more than 1000 records, no errors are thrown but the records will be missing for the stream. 

Workaround is to have a timeout set before posting to kinesis. So, it will slow down posting more than 1000 records per second to the shard of the stream.

@nonword, @kfriedman - we may have to test this on triggers to ensure that amazon is handling this, because we are probably throwing a callback error for a lambda only when we get the error from kinesis putRecords's callback function, which in this case isn't happening.

**Comment by kfriedman** [comment]
What do you mean "test this on triggers"?

This seems like this is mostly a complication of using a bulk operation like PutRecords where it's possible to exceed the 1,000 records per shard limit AND it does NOT throw an error (http://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html).

We probably need to make sure we're capturing the bulk error and mitigate this error by adding rate limiting, increasing shards, or just adding a delay.

Bulk operations are tricky.

**Comment by jmathewt** [comment]
Sorry I meant wouldn't this issue happen on any of our components running as lambdas that post to Kinesis? I am not sure what's the max batch size that can be set while using  Kinesis triggers for lambdas

**Comment by jmathewt** [comment]
I was talking to @kfriedman about this. If we have a stream with 3 shards and if they kick off 3 lambdas (through triggers) and each lambda does putRecords of 500 records at the same time to a stream with one shard at the same time, we will hit this issue.
